### ISSUE TITLE
anthropometry

### ISSUE THREAD

**Issue by websocketing** [VVingerfly/Triangulation#1]
I'm glad to see this project. I wonder if this project supports anthropometry? I need to measure the human parts of the generated manikin. I hope I can get your reply and information.

如果我没猜错，你应该来自中国，很高兴认识你，希望可以得到你的联系方式，进一步沟通。

**Comment by VVingerfly** [comment]
Hi, this repo contains code to triangulate points on a plane (generate a triangle mesh from planar points), it's not related to anthropometry. 
You can reach me at wei587me@163.com
